### ISSUE TITLE
run_oracle_response fails with "RVCount doesn't match with EvaluationStack"

### ISSUE THREAD

**Issue by 77696c6c** [CityOfZion/neo3-boa#654]
**Describe the bug**

I've been trying to get the following to work for the past couple of days and have no idea what is going wrong since it's just an empty skeleton. Every variant of my call of run_oracle_response fails with `RVCount doesn't match with EvaluationStack`.

```
======================================================================
ERROR: test_callback (test_oracle.TestTemplate)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/william/Neo/src/lyrebird-contract/testsrc/test_oracle.py", line 574, in test_callback
    self.run_oracle_response(engine, request_id, OracleResponseCode.Success, b'1')
  File "/Users/william/Neo/lib/neo3-boa-0.10.0/boa3_test/tests/boa_test.py", line 224, in run_oracle_response
    return self._filter_result(test_engine, expected_result_type, result)
  File "/Users/william/Neo/lib/neo3-boa-0.10.0/boa3_test/tests/boa_test.py", line 238, in _filter_result
    raise TestExecutionException(test_engine.error)
boa3_test.tests.test_classes.TestExecutionException.TestExecutionException: RVCount doesn't match with EvaluationStack
```

**How to Reproduce**

Oracle call
```
from typing import Any

from boa3.builtin import public
from boa3.builtin.interop.oracle import Oracle
from boa3.builtin.type import UInt160
from boa3.builtin.interop.runtime import log

@public
def onNEP17Payment(from_address: UInt160, amount: int, data: Any):
    Oracle.request('http://test.com', None, 'callback', [], 50_000_000)

@public
def callback(url: str, user_data: Any, code: int, result: bytes):
    log('callback')
```

Test code
```
    def test_callback(self):
        token_path = self.get_test_path()
        test_path = self.get_test_path()
        engine = TestEngine()

        #self.run_oracle_response(engine, 0, 0, json_serialize({ 'LRB': 100_000, 'LUSD': 1_000_000 }))
        engine.add_contract(token_path.replace('.py', '.nef'))
        engine.add_contract(test_path.replace('.py', '.nef'))

        output, manifest = self.compile_and_save(test_path)
        test_address = hash160(output)

        self.run_smart_contract(engine, token_path, '_deploy', None, False,
        signer_accounts=[self.OWNER_SCRIPT_HASH])
        
        self.run_smart_contract(engine, token_path, 'transfer', self.OWNER_SCRIPT_HASH, test_address, 1000, None,
                                         signer_accounts=[self.OWNER_SCRIPT_HASH])

        oracle_requests = engine.get_events('OracleRequest', constants.ORACLE_SCRIPT)
        self.assertEqual(1, len(oracle_requests))
        request_id = oracle_requests[0].arguments[0]

        self.run_oracle_response(engine, request_id, OracleResponseCode.Success, b'1')
        
```

**Expected Behavior**
Test success

**Platform**
Encountered on Python 3.8.12, boa 0.10, and neo-devpack-dotnet 3.0.2 on macOS 11.5.2.

**Comment by melanke** [comment]
This error ocurred only with testEngine and we dropped support to TestEngine in favor of TestRunner
