### ISSUE TITLE
Dev branch CLI broken

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#816]
**Describe the bug**
I cannot compile anything due to this error

```
Traceback (most recent call last):
  File "/home/erik/Documents/code/demo/boa/boa3/cli.py", line 26, in main
    Boa3.compile_and_save(args.input, args.debug)
  File "/home/erik/Documents/code/demo/boa/boa3/boa3.py", line 42, in compile_and_save
    elif not output_path.endswith('.nef'):
AttributeError: 'bool' object has no attribute 'endswith'
```

caused by 
https://github.com/CityOfZion/neo3-boa/blob/751828a2982f3149338cd68cdc164c50993a1826/boa3/cli.py#L24
should say
```python
 Boa3.compile_and_save(args.input, debug=args.debug) 
```
Currently the second argument `args.debug` is forced into the `output_path` argument of this function and therefore blows up

https://github.com/CityOfZion/neo3-boa/blob/751828a2982f3149338cd68cdc164c50993a1826/boa3/boa3.py#L25

**How to Reproduce**
Try to compile any contract using the cli

**Expected behavior**
compilation works

**Platform:**
 - OS: ubuntu 20.04
 - Version: Running `development` branch commit 751828a2982f3149338cd68cdc164c50993a1826 
 - Python version: 3.8.10

**Comment by ixje** [comment]
solved in 0b1ddbf72d66e75a78ca6e68cae48696eb1a0b4b
